title: Basic Containers 
patterns: ['**/*.md', '!**/node_modules', '!templates/**']
base: /basiccontainers/
themeConfig:
  repo: 'basiccontainers/basiccontainer.github.io'
  editLinks: true
  sidebar:
    [
      ['./', 'Home'],
      './webapps/',
      './aks/',
    ]
plugins: [['vuepress-plugin-code-copy', true]]
